import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
w1_path = np.array(pd.read_json("_w1_path.json"))
w2_path = np.array(pd.read_json("_w2_path.json"))
train_loss = np.array(pd.read_json("_train_loss.json"))
test_loss = np.array(pd.read_json("_test_loss.json"))
test_acc = np.array(pd.read_json("_test_acc.json"))
t = range(1000)
plt.figure(1)
ax1 = plt.subplot(321)
plt.plot(t,w1_path)
plt.xlabel("epoch")
plt.ylabel("Squared Frobenius Norm of w1")
ax2 = plt.subplot(322)
plt.plot(t,w2_path)
plt.xlabel("epoch")
plt.ylabel("Squared Frobenius Norm of w2")
ax3 = plt.subplot(323)
plt.plot(t,train_loss/60000)
plt.xlabel("epoch")
plt.ylabel("train loss")
ax4 = plt.subplot(324)
plt.plot(t,test_loss/10000)
plt.xlabel("epoch")
plt.ylabel("test loss")
ax5 = plt.subplot(313)
plt.plot(t,test_acc)
plt.xlabel("epoch")
plt.ylabel("test accuracy")
plt.show()